source = ~/.config/hypr/conf.d/variables.conf
source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/env.conf
source = ~/.config/hypr/conf.d/nvidia.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/appearance.conf
source = ~/.config/hypr/conf.d/autostart.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/rules.conf
